### ISSUE TITLE
compile err when install 

### ISSUE THREAD

**Issue by lotus-king** [murlokswarm/mac#12]
my system is os x 10.11.6
Xcode 7.3.1
Build version 7D1014

when install ,errors show below 

> $ go get -u github.com/murlokswarm/mac
> gopath/src/github.com/murlokswarm/mac/menu.m:138:41: error: use of undeclared identifier 'NSEventModifierFlagCommand'
> gopath/src/github.com/murlokswarm/mac/menu.m:140:41: error: use of undeclared identifier 'NSEventModifierFlagControl'
> gopath/src/github.com/murlokswarm/mac/menu.m:142:41: error: use of undeclared identifier 'NSEventModifierFlagOption'
> gopath/src/github.com/murlokswarm/mac/menu.m:144:41: error: use of undeclared identifier 'NSEventModifierFlagShift'
> gopath/src/github.com/murlokswarm/mac/menu.m:146:41: error: use of undeclared identifier 'NSEventModifierFlagFunction'

**Comment by maxence-charriere** [comment]
It requires OS X 10.12 and the latest version of Xcode.
See https://github.com/murlokswarm/app/issues/14

**Comment by lotus-king** [comment]
good job
