### ISSUE TITLE
Error when building: undefined: app.Componer

### ISSUE THREAD

**Issue by MihkelBaranov** [murlokswarm/mac#25]
When trying to build the hello world example from https://github.com/murlokswarm/app#hello-world the build fails.

OS: MacOS High Sierra 10.13.3 
```
$ goapp mac build
github.com/murlokswarm/mac
# github.com/murlokswarm/mac
picker.m:32:17: warning: 'NSFileHandlingPanelOKButton' is deprecated: first deprecated in macOS 10.13 [-Wdeprecated-declarations]
/System/Library/Frameworks/AppKit.framework/Headers/NSSavePanel.h:21:5: note: 'NSFileHandlingPanelOKButton' has been explicitly marked deprecated here
# github.com/murlokswarm/mac
../../murlokswarm/mac/menu.go:24: undefined: app.Componer
exit status 2
```

**Comment by maxence-charriere** [comment]
This repo is not used anymore. The mac driver has been moved into the app package.

Sent from my iPhone

On Jul 5, 2018, at 12:02 AM, Mihkel <notifications@github.com<mailto:notifications@github.com>> wrote:


When trying to build the hello world example from https://github.com/murlokswarm/app#hello-world the build fails.

OS: MacOS High Sierra 10.13.3

$ goapp mac build
github.com/murlokswarm/mac<http://github.com/murlokswarm/mac>
# github.com/murlokswarm/mac<http://github.com/murlokswarm/mac>
picker.m:32:17: warning: 'NSFileHandlingPanelOKButton' is deprecated: first deprecated in macOS 10.13 [-Wdeprecated-declarations]
/System/Library/Frameworks/AppKit.framework/Headers/NSSavePanel.h:21:5: note: 'NSFileHandlingPanelOKButton' has been explicitly marked deprecated here
# github.com/murlokswarm/mac<http://github.com/murlokswarm/mac>
../../murlokswarm/mac/menu.go:24: undefined: app.Componer
exit status 2
